#!/usr/bin/env python3
"""Generate twiddle factor hex file for an N-point FFT in fixed-point format.

Produces a Verilog $readmemh-compatible hex file containing cos/sin twiddle
factors for indices 0 .. N/2-1 (the first N/2 roots of unity needed by a
radix-2 / radix-4 DIT FFT).

Usage:
    python scripts/gen_twiddles.py --n 256 --format Q8.8
    python scripts/gen_twiddles.py --n 256 --format Q4.4 --output custom.hex

The default output path is rtl/twiddle_data/twiddle_<N>.hex, relative to the
project root (parent of the script directory).
"""

import argparse
import math
import os
import sys


# ---------------------------------------------------------------------------
# Fixed-point helpers
# ---------------------------------------------------------------------------

def parse_format(fmt):
    """Parse a Qm.n format string like 'Q8.8' into (total_bits, frac_bits)."""
    fmt = fmt.strip().upper().replace("Q", "")
    if "." not in fmt:
        raise ValueError(f"format must be like Q8.8, got '{fmt}'")
    int_bits, frac_bits = fmt.split(".")
    int_bits = int(int_bits)
    frac_bits = int(frac_bits)
    total_bits = int_bits + frac_bits
    if total_bits not in (8, 16, 32):
        print(
            f"Warning: unusual total width {total_bits} bits "
            f"({fmt}) — Verilog $readmemh supports arbitrary widths.",
            file=sys.stderr,
        )
    return total_bits, frac_bits


def to_fixed(value, total_bits, frac_bits):
    """Convert a float in [-1, 1] to a two's-complement fixed-point integer."""
    scale = 1 << frac_bits
    raw = int(round(value * scale))
    max_val = (1 << (total_bits - 1)) - 1
    min_val = -(1 << (total_bits - 1))
    if raw > max_val:
        raw = max_val
    if raw < min_val:
        raw = min_val
    if raw < 0:
        raw += (1 << total_bits)
    return raw


def to_hex(value, total_bits):
    """Format a fixed-point integer as a hex string."""
    nibbles = (total_bits + 3) // 4
    return f"{value:0{nibbles}X}"


# ---------------------------------------------------------------------------
# Twiddle generation
# ---------------------------------------------------------------------------

def generate_twiddles(n, total_bits, frac_bits):
    """Return list of (cos_hex, sin_hex) for twiddle indices 0..n/2-1."""
    twiddles = []
    for k in range(n // 2):
        angle = -2.0 * math.pi * k / n
        cos_val = math.cos(angle)
        sin_val = math.sin(angle)
        cos_fixed = to_fixed(cos_val, total_bits, frac_bits)
        sin_fixed = to_fixed(sin_val, total_bits, frac_bits)
        twiddles.append((to_hex(cos_fixed, total_bits), to_hex(sin_fixed, total_bits)))
    return twiddles


def write_hex_file(twiddles, path, total_bits):
    """Write twiddle factors as a $readmemh-compatible hex file.

    Format: one twiddle per line as {cos, sin} concatenated, or two lines per
    twiddle (cos, sin) depending on convention. Here we use a single combined
    word per twiddle: upper bits = cos, lower bits = sin.
    """
    nibbles = (total_bits + 3) // 4
    with open(path, "w") as f:
        f.write(f"// Twiddle factors for {len(twiddles) * 2}-point FFT\n")
        f.write(f"// Format: Q{total_bits - (total_bits // 2)}.{total_bits // 2} fixed-point\n")
        f.write(f"// Each line: cos (upper {nibbles} hex digits)\n")
        f.write(f"// Generated by gen_twiddles.py\n\n")
        for i, (cos_hex, sin_hex) in enumerate(twiddles):
            f.write(f"{cos_hex}  // index {i:4d} cos\n")
            f.write(f"{sin_hex}  // index {i:4d} sin\n")
    return path


def write_combined_hex_file(twiddles, path, total_bits):
    """Write twiddle factors as combined {cos, sin} words (one per line)."""
    nibbles = (total_bits + 3) // 4
    with open(path, "w") as f:
        f.write(f"// Twiddle factors for N={len(twiddles) * 2}\n")
        f.write(f"// Q format: {total_bits}-bit total, combined cos||sin\n")
        f.write(f"// Generated by gen_twiddles.py\n\n")
        for i, (cos_hex, sin_hex) in enumerate(twiddles):
            combined = cos_hex + sin_hex
            f.write(f"{combined}  // index {i:4d}\n")
    return path


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(
        description="Generate twiddle factor hex file for N-point FFT."
    )
    parser.add_argument(
        "--n", type=int, default=256,
        help="FFT size N (must be a power of 2). Default: 256"
    )
    parser.add_argument(
        "--format", type=str, default="Q8.8",
        help="Fixed-point format, e.g. Q8.8 or Q4.4. Default: Q8.8"
    )
    parser.add_argument(
        "--output", type=str, default=None,
        help="Output hex file path. Default: rtl/twiddle_data/twiddle_<N>.hex"
    )
    parser.add_argument(
        "--combined", action="store_true",
        help="Output combined cos||sin words instead of interleaved."
    )
    args = parser.parse_args()

    # Validate N is a power of 2
    if args.n <= 0 or (args.n & (args.n - 1)) != 0:
        print(f"Error: N={args.n} must be a positive power of 2.", file=sys.stderr)
        sys.exit(1)

    total_bits, frac_bits = parse_format(args.format)

    # Determine output path
    if args.output:
        out_path = args.output
    else:
        script_dir = os.path.dirname(os.path.abspath(__file__))
        project_root = os.path.dirname(script_dir)
        out_dir = os.path.join(project_root, "rtl", "twiddle_data")
        out_path = os.path.join(out_dir, f"twiddle_{args.n}.hex")

    # Generate
    twiddles = generate_twiddles(args.n, total_bits, frac_bits)

    # Ensure output directory exists
    os.makedirs(os.path.dirname(out_path) if os.path.dirname(out_path) else ".", exist_ok=True)

    if args.combined:
        write_combined_hex_file(twiddles, out_path, total_bits)
    else:
        write_hex_file(twiddles, out_path, total_bits)

    print(f"Generated {len(twiddles)} twiddle factors for N={args.n}")
    print(f"Format: {args.format} ({total_bits} bits, {frac_bits} fractional)")
    print(f"Output: {out_path}")

    # Print first few for verification
    print("\nFirst 8 twiddle factors (cos, sin):")
    for i, (cos_hex, sin_hex) in enumerate(twiddles[:8]):
        angle = -2.0 * math.pi * i / args.n
        print(f"  [{i:3d}] cos={cos_hex} sin={sin_hex}  (float: {math.cos(angle):.4f}, {math.sin(angle):.4f})")


if __name__ == "__main__":
    main()