"""Cocotb testbench for batch_channel_controller.v — Batch Channel Sequencer.

Verifies that the batch_channel_controller:
  1. Processes channels sequentially (0, 1, 2, ... chan_cnt-1).
  2. Asserts all_done after all channels complete.
  3. Produces the correct channel_id sequence on the output port.

The DUT is `batch_channel_controller`.  A lightweight mock spectral_mixer
and dual-port RAMs are instantiated in the companion Verilog TB wrapper
(batch_tb_wrap.v, generated by this testbench's Makefile) so we can exercise
the controller's handshake without the full pipeline.

Run with:
    make SIM=icarus TOPLEVEL=batch_channel_controller TB=tb_batch_channel

Makefile snippet (add to project Makefile):

    # Batch channel controller cocotb test
    sim_batch_cocotb:
        cd tb && SIM=icarus TOPLEVEL=batch_channel_controller \
            MODULE=tb_batch_channel \
            COMPILE_ARGS="-g2012 rtl/batch_channel_controller.v tb/batch_tb_wrap.v" \
            pytest tb_batch_channel.py

    # Or via cocotb-test:
    sim_batch_pytest:
        pytest tb/tb_batch_channel.py

    # Plain iverilog smoke test (wrapper + controller, self-checking)
    sim_batch_iverilog:
        iverilog -g2012 -o sim_batch \
            rtl/batch_channel_controller.v tb/batch_tb_wrap.v
        vvp sim_batch
"""

import os

import cocotb
from cocotb.clock import Clock
from cocotb.triggers import ClockCycles, RisingEdge, FallingEdge, Timer, First


# ---------------------------------------------------------------------------
# Parameters (must match RTL defaults)
# ---------------------------------------------------------------------------

N_SAMPLES = 256       # samples per channel
N_CHANNELS_DEFAULT = 64
CLK_PERIOD_NS = 10    # 100 MHz


# ---------------------------------------------------------------------------
# Clock and reset
# ---------------------------------------------------------------------------

async def setup_dut(dut):
    """Start the clock and assert/deassert reset."""
    cocotb.start_soon(Clock(dut.clk, CLK_PERIOD_NS, units="ns").start())
    dut.rst_n.value = 0
    dut.start.value = 0
    dut.chan_cnt.value = N_CHANNELS_DEFAULT
    dut.mixer_done.value = 0
    # Drive RAM read data to zero initially
    if hasattr(dut, "ram_rd_re"):
        dut.ram_rd_re.value = 0
    if hasattr(dut, "ram_rd_im"):
        dut.ram_rd_im.value = 0
    await ClockCycles(dut.clk, 5)
    dut.rst_n.value = 1
    await ClockCycles(dut.clk, 5)


# ---------------------------------------------------------------------------
# Mock spectral mixer: respond to mixer_start with mixer_done after a delay
# ---------------------------------------------------------------------------

async def mock_mixer(dut, delay_cycles=10, max_channels=128):
    """Background coroutine that simulates the spectral_mixer handshake.

    On each rising edge of mixer_start, waits `delay_cycles` clocks, then
    pulses mixer_done for one cycle.
    """
    while True:
        # Wait for mixer_start to go high
        await RisingEdge(dut.mixer_start)
        dut._log.debug("mock_mixer: got mixer_start")
        await ClockCycles(dut.clk, delay_cycles)
        dut.mixer_done.value = 1
        await RisingEdge(dut.clk)
        dut.mixer_done.value = 0


# ---------------------------------------------------------------------------
# Tests
# ---------------------------------------------------------------------------

@cocotb.test()
async def test_sequential_channel_processing(dut):
    """Test 1: Channels are processed sequentially (0, 1, 2, ...)."""
    await setup_dut(dut)

    n_channels = 4  # Use 4 channels for speed
    dut.chan_cnt.value = n_channels
    await RisingEdge(dut.clk)

    # Start the mock mixer in the background
    cocotb.start_soon(mock_mixer(dut, delay_cycles=10))

    observed_channels = []

    # Issue start pulse
    dut.start.value = 1
    await RisingEdge(dut.clk)
    dut.start.value = 0

    # Monitor channel_id changes until all_done
    timeout = 5000
    for _ in range(timeout):
        if dut.all_done.value == 1:
            break
        # Record channel_id whenever busy is high and we see a new channel
        if dut.busy.value == 1:
            cur_chan = int(dut.channel_id.value)
            if not observed_channels or observed_channels[-1] != cur_chan:
                observed_channels.append(cur_chan)
        await RisingEdge(dut.clk)

    dut._log.info(f"Observed channels: {observed_channels}")
    assert dut.all_done.value == 1, "all_done did not assert within timeout"

    # Verify channels were processed sequentially 0..n_channels-1
    expected = list(range(n_channels))
    # observed_channels may have duplicates at boundaries; deduce the
    # set of unique channels that appeared while busy
    assert set(observed_channels) == set(expected), \
        f"Channels not sequential: got {observed_channels}, expected {expected}"

    dut._log.info(f"PASS: {n_channels} channels processed sequentially")


@cocotb.test()
async def test_all_done_asserts(dut):
    """Test 2: all_done asserts after all channels complete."""
    await setup_dut(dut)

    n_channels = 8
    dut.chan_cnt.value = n_channels
    await RisingEdge(dut.clk)

    cocotb.start_soon(mock_mixer(dut, delay_cycles=8))

    # Issue start
    dut.start.value = 1
    await RisingEdge(dut.clk)
    dut.start.value = 0

    # Wait for all_done with generous timeout
    # Each channel: 256 (load) + 8 (wait) + 256 (store) + 1 (next) ≈ 521 cycles
    # 8 channels ≈ 4168 cycles; give 2× margin
    timeout_cycles = n_channels * 256 * 3 + 5000
    all_done_seen = False

    for i in range(timeout_cycles):
        if dut.all_done.value == 1:
            all_done_seen = True
            break
        await RisingEdge(dut.clk)

    assert all_done_seen, \
        f"all_done did not assert within {timeout_cycles} cycles"
    dut._log.info(f"PASS: all_done asserted after {n_channels} channels")


@cocotb.test()
async def test_channel_id_sequence(dut):
    """Test 3: Correct channel_id sequencing — verify exact 0..N-1 order."""
    await setup_dut(dut)

    n_channels = 6
    dut.chan_cnt.value = n_channels
    await RisingEdge(dut.clk)

    cocotb.start_soon(mock_mixer(dut, delay_cycles=5))

    channel_sequence = []
    last_recorded = -1

    dut.start.value = 1
    await RisingEdge(dut.clk)
    dut.start.value = 0

    timeout_cycles = n_channels * 256 * 3 + 5000
    for _ in range(timeout_cycles):
        if dut.all_done.value == 1:
            break
        if dut.busy.value == 1:
            cur = int(dut.channel_id.value)
            if cur != last_recorded:
                channel_sequence.append(cur)
                last_recorded = cur
        await RisingEdge(dut.clk)

    dut._log.info(f"channel_id sequence: {channel_sequence}")

    # The sequence should be exactly [0, 1, 2, ..., n_channels-1]
    expected_seq = list(range(n_channels))
    assert channel_sequence == expected_seq, \
        f"channel_id sequence mismatch: got {channel_sequence}, " \
        f"expected {expected_seq}"

    dut._log.info(f"PASS: channel_id sequence = {expected_seq}")


@cocotb.test()
async def test_default_channel_count(dut):
    """Test 4: Default channel count (64) processes all 64 channels."""
    await setup_dut(dut)

    # Use the RTL default of 64 channels
    dut.chan_cnt.value = 64
    await RisingEdge(dut.clk)

    # Use a short mixer delay to keep sim time reasonable
    cocotb.start_soon(mock_mixer(dut, delay_cycles=2))

    max_chan_seen = -1
    dut.start.value = 1
    await RisingEdge(dut.clk)
    dut.start.value = 0

    # 64 channels × (256 load + 2 wait + 256 store + 1 next) ≈ 64 × 515 ≈ 33K
    timeout_cycles = 64 * 600 + 5000
    for _ in range(timeout_cycles):
        if dut.all_done.value == 1:
            break
        if dut.busy.value == 1:
            cur = int(dut.channel_id.value)
            if cur > max_chan_seen:
                max_chan_seen = cur
        await RisingEdge(dut.clk)

    assert dut.all_done.value == 1, "all_done did not assert for 64 channels"
    assert max_chan_seen == 63, \
        f"Expected max channel 63, got {max_chan_seen}"

    dut._log.info(f"PASS: all 64 channels processed (max channel_id = {max_chan_seen})")


@cocotb.test()
async def test_busy_signal(dut):
    """Test 5: busy is high during processing and low when done."""
    await setup_dut(dut)

    dut.chan_cnt.value = 3
    await RisingEdge(dut.clk)

    cocotb.start_soon(mock_mixer(dut, delay_cycles=5))

    # Before start, busy should be low
    assert dut.busy.value == 0, "busy should be low before start"

    dut.start.value = 1
    await RisingEdge(dut.clk)
    dut.start.value = 0

    # Wait a few cycles — busy should go high
    await ClockCycles(dut.clk, 3)
    assert dut.busy.value == 1, "busy should be high during processing"

    # Wait for all_done
    timeout_cycles = 3 * 600 + 2000
    for _ in range(timeout_cycles):
        if dut.all_done.value == 1:
            break
        await RisingEdge(dut.clk)

    assert dut.all_done.value == 1, "all_done did not assert"
    # After all_done, busy should be low
    await ClockCycles(dut.clk, 2)
    assert dut.busy.value == 0, "busy should be low after completion"

    dut._log.info("PASS: busy signal correctly tracked processing state")